version: '3'

services:

  mongo:
    image: mongo-regbox
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  mongo-data:

