version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    image: mongo-regbox
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd

volumes:
  mongo-data:
